#! /bin/sh

shopt -s huponexit

bspc config border_width		2
bspc config window_gap			5
bspc config top_padding			12
bspc config bottom_padding		-5
bspc config left_padding		-5
bspc config right_padding		-5
bspc config split_ratio			0.50
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true
bspc config focused_border_color	'#b8bb26'

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

lemonbuddy_wrapper bar &

xsetroot -cursor_name left_ptr
setxkbmap hr

sh ~/.fehbg &

sxhkd &
