#! /bin/sh

shopt -s huponexit

bspc config border_width		2
bspc config window_gap			5
bspc config top_padding			5
bspc config bottom_padding		-5
bspc config left_padding		-5
bspc config right_padding		-5
bspc config split_ratio			0.50
bspc config focus_follows_pointer	true
bspc config focused_border_color	'#82aaff'
bspc config presel_feedback_color	'#82aaff'
bspc config pointer_modifier		mod1
bspc config pointer_action1		move

bspc rule -a skypeforlinux:skypeforlinux desktop=^8
bspc rule -a Thunderbird:* desktop=^9

ext=$(xrandr  | grep ^HDMI | awk '{print $2}')
if [ "$ext" == "connected" ]; then
	bspc monitor HDMI1 -d 1 2 3 4 5
	bspc monitor eDP1 -d 6 7 8 9 0
else
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi


xsetroot -cursor_name left_ptr
setxkbmap hr

sh ~/.fehbg &

sxhkd -m -1 &

polybar ext &
polybar main &

compton -b

skypeforlinux &
thunderbird &
